services:
  - type: web
    name: deriv-trading-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k gthread -w 1 app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
